log-level: debug
pipeline:
  ingest:
    type: file
    file:
      filename: playground/aws1_input.txt
  decode:
    type: aws
    aws:
      fields:
        - version
        - account-id
        - interface-id
        - srcaddr
        - dstaddr
        - srcport
        - dstport
        - protocol
        - packets
        - bytes
        - start
        - end
        - action
        - log-status
  transform:
    - type: none
  extract:
    type: none
  encode:
    type: none
  write:
    type: stdout

