log-level: debug
pipeline:
  ingest:
    type: file
    file:
      filename: playground/goflow2_input.txt
  decode:
    type: json
  transform:
    - type: generic
      generic:
        - input: Bytes
          output: flp_bytes
        - input: DstAddr
          output: flp_dstAddr
        - input: DstHostIP
          output: flp_dstHostIP
        - input: DstPort
          output: flp_dstPort
        - input: Packets
          output: flp_packets
        - input: SrcAddr
          output: flp_srcAddr
        - input: SrcHostIP
          output: flp_srcHostIP
        - input: SrcPort
          output: flp_srcPort
        - input: TimeReceived
          output: flp_timestamp
  extract:
    type: none
  encode:
    type: none
  write:
    type: stdout

