name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.7']
        
    steps:
    - name: Install make
      run: sudo apt-get install make
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - uses: actions/checkout@v2

    - name: Run build
      run: make build
      
    - name: Run test
      run: make test
