name: Check pull request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.17']
        
    steps:
    - name: install make
      run: sudo apt-get install make
    - name: set up go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: checkout
      uses: actions/checkout@v2
    - name: run build
      run: make build
    - name: run test
      run: make test
